/***********************************************************************/
/*                                                                     */
/*  FILE        :r_apn_grobal.h                                        */
/*  DATE        :Wed, Apr 21, 2010                                     */
/*  DESCRIPTION :Global header file                                    */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.50).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#ifndef R_APN_GROBAL_DEF
#define R_APN_GROBAL_DEF

#include "iodefine.h"
#include <stdint.h>
#include <stdbool.h>

#endif  /* R_APN_GROBAL_DEF */
